# Generated by Django 5.0 on 2024-01-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('auteurs', models.CharField(max_length=500)),
                ('institutions', models.CharField(max_length=500)),
                ('mots_cles', models.CharField(max_length=200)),
                ('texte_integral', models.TextField()),
                ('url_pdf', models.TextField()),
                ('references_bibliographiques', models.TextField()),
            ],
        ),
    ]
