# Generated by Django 4.2.7 on 2024-02-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleStock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
