# Generated by Django 5.0 on 2024-01-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleStock', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='ArticleStock.article'),
        ),
    ]
