# Generated by Django 5.0.1 on 2024-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_favorite_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_articles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
