# Generated by Django 5.0.1 on 2024-01-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_favorite_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
